version: '3'
services:
    postgres:
        image: 'postgres:latest'
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD='password'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    redis:
        image: 'redis:latest'
    api:
        build: 
            context: ./server/  #specifiy the directory where the files should be pulled from
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app #Workdir!
        restart: on-failure
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD='password'
            - PGPORT=5432
        depends_on: 
            - postgres
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
    nginx:
        depends_on: 
            - api 
            - client
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - '80:80'
        restart: always

